### ISSUE TITLE
Add GitHub workflow to test gx-scs.okeanos.dev

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/openstack-health-monitor#1]

**Comment by joshmue** [comment]
Related:

The CI tests of https://github.com/SovereignCloudStack/k8s-os-health-monitor are testing gx-scs.okeanos.dev now. The focus of the solution may vary, though. Right now, everything is considered working as soon as API requests are counted.

**Comment by tibeer** [comment]
@berendt Can this be closed?

**Comment by garloff** [comment]
We should have health-monitoring as part of our CI in zuul, IMVHO.
Let's look at this again when we start rolling our zuul usage more broadly after R3.
