### ISSUE TITLE
Allow use of volume types

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/openstack-health-monitor#139]
When booting from volumes at the moment it is not possible to define the used volume type. It should be possible to define the volume type for the test nodes as well as for the jump node.

**Comment by garloff** [comment]
This look reasonably easy to so.
`--block-device` allows for a volume type on `server create` (for diskless flavors) and of course we can control it when creating volumes manually (`openstack volume create`).
I guess the easiest way would be to allow setting this via an environment variable.

**Comment by garloff** [comment]
Addressed by #172
