### ISSUE TITLE
Using ApplicationCredentials will fail

### ISSUE THREAD

**Issue by chrisschwa** [SovereignCloudStack/openstack-health-monitor#144]
When you use Application Credentials the api_monitor script fails with and Error 

> source OS_ settings file before running this test

The Problem is a Test on a specific Variable `OS_USERNAME` which is not present in a ApplicationCred Scenario.
Commenting that out will fix the issue and you can use ApplicationCredentials.

```
#if test -z "$OS_USERNAME" -a -z "$OS_CLOUD"; then
# echo "source OS_ settings file before running this test"
# exit 1
#fi
```

**Comment by chrisschwa** [comment]
We should Check if `OS_AUTH_TYPE=v3applicationcredential` and when NOT we check for Username, else we check for 
`OS_APPLICATION_CREDENTIAL_ID` and `OS_APPLICATION_CREDENTIAL_SECRET`

**Comment by garloff** [comment]
Auth via `OS_USERNAME` and `OS_PASSWORD` should not be used. Please set `auth_type: v3applicationcredential` in your `~/.config/openststack/clouds.yaml` instead and pass `OS_CLOUD`.

**Comment by garloff** [comment]
But we can also allow appcreds via OS_ variables. #157
