### ISSUE TITLE
Image with version tag

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/openstack-health-monitor#66]
We are currently cleaning up the images in OSISM and making sure that version tags are used in all places instead of the latest tag.

The image for the openstack-health-monitor is only available with latest tag and the build of it is already 8 months ago.

https://quay.io/repository/sovereigncloudstack/openstack-health-monitor?tab=tags

* the latest tag should be regularly rebuilt
* there should be tags with versions

**Comment by fkr** [comment]
@berendt has a valid point imho.
@garloff how about you tag a version as of now, so that this can be referenced?

**Comment by fkr** [comment]
@garloff then we just need to update the image up on quay.io. I've not been involved in the flow so far. Who is updating the images there?

**Comment by berendt** [comment]
The upload job has been disabled. I have reactivated it. A job to push versioned images does not exist yet.

I would suggest that I sync all the Github workflows here in this repository with what we are currently using.

Then there is also a job to push versioned tags.

![Bildschirmfoto 2022-03-30 um 09 38 30](https://user-images.githubusercontent.com/419091/160777635-d8e7c1a8-eca2-4405-b299-1110d388bf55.png)
